### ISSUE TITLE
Running on snap datasets

### ISSUE THREAD

**Issue by florianre** [frankmcsherry/differential-dataflow#102]
I am running the command:
`cargo run --release --example cc -- ~/Projects/Datasets/wiki-Vote.txt`, wiki-Vote.txt being a snap dataset. However, I get the following error:
`Finished release [optimized + debuginfo] target(s) in 0.0 secs
Running target/release/examples/cc /home/fre14/Individual-Project/Graph-Database-Ext/datasets/wiki-Vote.txt
thread 'worker thread 0' panicked at 'error opening file', libcore/option.rs:917:5
note: Run with RUST_BACKTRACE=1 for a backtrace.
thread 'main' panicked at 'called Result::unwrap() on an Err value: Any', libcore/result.rs:945`
What am I doing wrong? Is there a command I am supposed to run beforehand?

Thank you

**Comment by frankmcsherry** [comment]
Hi!

The most obvious thing that stands out is that the `~/Projects/Datasets/` is a directory structure I have on my laptop, and you may not have. It sounds like the program is having a hard time opening the filename provided, and if that file doesn't exist there things will break.

A second issue is that if you are using the github master (vs the version from crates.io) then it will want to use the `GraphMap` format. 

https://github.com/frankmcsherry/differential-dataflow/blob/master/examples/cc.rs#L30

This is a binary layout that can be efficiently memmapped in. To get it in that format I'd swing by the [graph_map repository](https://github.com/frankmcsherry/graph-map) which should be quick to build, and have a binary `parse` for which you can type

    cargo run --release --bin parse -- path/to/WikiVote.txt path/to/binary_output

This should go and process the file and drop it in graph_map format, at which point you can run cc with `path/to/binary_output`.

Sorry for the confusion. The examples are a bit of a mix of "shows how DD works" and "might run for you with help", but aren't exactly freestanding analyses.

**Comment by florianre** [comment]
Thank you very much! It works now 💯
