### ISSUE TITLE
Question: SIMD support in the worker

### ISSUE THREAD

**Issue by codri** [frankmcsherry/differential-dataflow#109]
Looking at it can't find any reference of SIMD support in the worker.

Haven't had the chance to look more thoroughly at the project, but I assume it serializes the worker task and sends it accross the network(i'm interested in the distributed usage) where the job is launched as a thread.

It would be great to also be able to execute SIMD within each thread, as usually each physical core has a SIMD engine.

Is SIMD supported in workers? If, so, how about libraries like faster(https://github.com/AdamNiederer/faster)

**Comment by frankmcsherry** [comment]
The workers run the code that you write. If you write code that uses SIMD, they will use SIMD.

**Comment by codri** [comment]
Great, thank you.
