### ISSUE TITLE
What command is needed to run a ``cc" test on a snap format graph? I am sorry I am totally new to rust ... 

### ISSUE THREAD

**Issue by asherliu** [frankmcsherry/differential-dataflow#11]

**Comment by frankmcsherry** [comment]
Hello.

The `cc` example uses the "graph map" format that I've been using, which just memory-maps an adjacency list representation, and whose details are available at:

```
[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"
```

This repo has tools (specifically https://github.com/frankmcsherry/graph-map/blob/master/src/bin/parse.rs) for taking text data whose lines have the form 

```
src dst
```

to the required format, with the requirement that the text lines be initially sorted. Not all snap formatted graphs have this property, so you should either (i) check that do and `sort -n` them if not, or (ii) tweak the code to do a sort for you (e.g. add a `graph.sort()` on line 30 of `parse.rs`).

Once the data are in this format, you should be able to supply the name to `cc` as an argument, like so:

```
Echidnatron% time cargo run --release --example cc -- ~/Projects/Datasets/livejournal
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/examples/cc /Users/mcsherry/Projects/Datasets/livejournal`
cargo run --release --example cc -- ~/Projects/Datasets/livejournal  16.73s user 3.05s system 98% cpu 20.002 total
Echidnatron%
```

**Comment by shamrin** [comment]
I was a little confused by the above explanation. But I've figured it out at the end. Here is how to download and prepare livejournal dataset at `~/src/datasets/livejournal` location:

```
mkdir -p ~/src/datasets
cd ~/src/datasets
curl -O https://snap.stanford.edu/data/soc-LiveJournal1.txt.gz
gunzip soc-LiveJournal1.txt.gz 

cd ~/src
git clone https://github.com/frankmcsherry/graph-map.git
cd graph-map
cargo run --release --bin parse ~/src/datasets/soc-LiveJournal1.txt ~/src/datasets/livejournal sort
```

Then `cc` example worked as expected:

```
cd ~/src
git clone https://github.com/frankmcsherry/differential-dataflow.git
cd differential-dataflow
git checkout 8c4c83fc # because examples moved around since that time
time cargo run --release --example cc -- ~/src/datasets/livejournal
    Finished release [optimized + debuginfo] target(s) in 0.16s                                                                                                                                                 
     Running `target/release/examples/cc ~/src/datasets/livejournal`
       56.33 real        49.47 user         4.99 sys
```
