### ISSUE TITLE
iterate doesn't converge on docs example

### ISSUE THREAD

**Issue by gandro** [frankmcsherry/differential-dataflow#14]
The `iterate` operator doesn't seem to terminate for many supposedly converging functions. Instead, it endlessly removes and re-adds the elements yielded by the computation.

Example (taken from the documentation of [`iterate`](http://www.frankmcsherry.org/differential-dataflow/differential_dataflow/operators/iterate/index.html)):

```rust
extern crate timely;
extern crate differential_dataflow;

use differential_dataflow::AsCollection;
use differential_dataflow::operators::*;
use timely::dataflow::operators::*;

fn main() {
    timely::example(|scope| {
        let numbers = (0..5).map(|x| (x, 1)).to_stream(scope).as_collection();

        numbers.iterate(|values| {
            values
                .map(|x| if x % 2 == 0 { x/2 } else { x })
                .inspect_batch(|ts ,x| println!("{:?}: {:?}", ts, x))
        });
    });
}
```
Output:
```
((Root, 0), 0): [(0, 1), (1, 1), (1, 1), (3, 1), (2, 1)]
((Root, 0), 1): [(0, -1), (1, -1), (1, -1), (3, -1), (2, -1), (0, 1), (1, 1), (1, 1), (3, 1), (1, 1)]
((Root, 0), 2): [(0, -1), (1, -1), (1, -1), (3, -1), (1, -1), (0, 1), (1, 1), (1, 1), (3, 1), (1, 1)]
((Root, 0), 3): [(0, -1), (1, -1), (1, -1), (3, -1), (1, -1), (0, 1), (1, 1), (1, 1), (3, 1), (1, 1)]
((Root, 0), 4): [(0, -1), (1, -1), (1, -1), (3, -1), (1, -1), (0, 1), (1, 1), (1, 1), (3, 1), (1, 1)]
…
```

It goes on like this forever, while I would expect it to stop producing updates at some point.

If one uses a compacting operator like `consolidate`, `group` or `distinct` in the loop body, then the negating deltas eventually disappear in the materialized form and the underlying stream ceases to produce updates.

I'm not sure if this is an actual bug or just a case of "you're holding it wrong" :) If it is the users' responsibility to compact, then we should probably update the documentation to reflect this.

**Comment by frankmcsherry** [comment]
So, this is because Iterate itself does not introduce a "consolidate" operator, because it's work is redundant with operators like group and join. I'm happy to update the docs, or find a better solution (eg attributes on collections). We could always add a consolidate, if the were a way for consolidating operators to opt out.

The same thing can happen in timely, if you have no buffering operator on the cycle (eg just a feedback). That is also not well documented (ie at all).

Lets keep the issue open until the situation improves!

**Comment by frankmcsherry** [comment]
I read this on the phone, and it didn't click that the docs example literally doesn't work. That will be fixed!
