### ISSUE TITLE
failed to execute the bfs example

### ISSUE THREAD

**Issue by mitake** [frankmcsherry/differential-dataflow#4]
Hi,

I tried to execute the bfs example as described in README but it failed. cargo complains that the required radix sort repository is deleted. Is it possible to recover the repository?

Below is an error message:
```
$ cargo run --release --example bfs
    Updating git repository `https://github.com/frankmcsherry/graph-map.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/frankmcsherry/radix-sort.git`
Unable to update https://github.com/frankmcsherry/radix-sort.git

Caused by:
  failed to clone into: /Users/mitake/.cargo/git/db/radix-sort-544b6b7f8774bde6

Caused by:
  failed to authenticate when downloading repository

To learn more, run the command again with --verbose.
```

**Comment by frankmcsherry** [comment]
Hello! 

Sorry about the confusion. I'm rolling over a bunch of repos for Rust 1.6. There is a new version just pushed which fixes this issue. 

There is *another* issue, though, which is that my README.md example doesn't apply to the current BFS code. It does something a bit different now. I'll clean up the documentation, but if you are interested in BFS you can run it like 

    cargo run --release --example bfs <nodes> <edges> <waves>

where `<nodes>` and  `<edges>` are nodes and edges for a random graph, and `<waves>` is the number of incremental updates you would like to do at a time (e.g. `1000` is a fun number).

For example:

    Echidnatron% cargo run --release --example bfs 1000000 2000000 1000
         Running `target/release/examples/bfs 1000000 2000000 1000`
    performing BFS on 1000000 nodes, 2000000 edges:
    loaded; elapsed: 0.10070752399769844s
    stable; elapsed: 0.2504105659972993s
    wave 0: avg 0.00001080268899386283
    wave 1: avg 0.000000278651001281105
    wave 2: avg 0.00000021916999685345217
    wave 3: avg 0.00000021864700102014468
    wave 4: avg 0.00000022478799655800686
    wave 5: avg 0.00000021842100250069052
    wave 6: avg 0.00000024789999588392676
    wave 7: avg 0.00000024084100004984064
    wave 8: avg 0.00000023841600341256708
    wave 9: avg 0.00000023135000083129853

**Comment by frankmcsherry** [comment]
I just rev'd the BFS example so that it prints out stuff a bit more like in the old README.md. I also rev'd the readme to reflect the new BFS. The algorithm is basically the same, but what it does (and how it does it) are just a little bit different. I hope the spirit is the same, though!

**Comment by mitake** [comment]
Hi @frankmcsherry , thanks for your reply and update! Now the BFS example seems to work fine on my machine so I'm playing with it :)
