### ISSUE TITLE
Proposal: Shared Arrangements

### ISSUE THREAD

**Issue by frankmcsherry** [frankmcsherry/differential-dataflow#44]
Differential dataflow manages its state through the `arrange` operator, which takes a disordered stream of timestamped updates, and produces a sequence of batches of organized, consolidated updates. These batches are also integrated into a `T: Trace` the `arrange` operator manages, and which is shared with downstream operators. The `arrange` operator handles common work like merging and advancing ("garbage collection") of these batches, so that each of the consumer operators do not have to. The bundle of stream and trace is called an `Arrangement`. 

There is currently the structural restriction that to use an arrangement, you must be in the same timely dataflow scope, because the stream is branded with the scope and can only be used there. However, the batches and the trace are only branded with the timestamp, and could in principle be used in any other scope with the same timestamp.

This proposal starts to detail how we might enable the sharing of traces and batch sequences with dataflow graphs and scopes other than that in which the data are arranged. 

--- 

The design and implementation of current trace and batch types make extensive use of `Rc<_>` reference counting shared ownership, so that the references can be shared within the worker (the boundary for an `Rc<_>` type is a thread of control). This is what allows us to share references to the trace among operators, to share references to batches between the trace and the channels out of the arrange operator, and various other sharing moments (e.g. cursors clone ref-counted pointers to simplify their lifetime story). Reference counted shared ownership is read-only, and associated resources are collected when the last of the referring owners gets dropped.

All of this means that there is nothing obviously hard about *sharing* this data between multiple dataflow scopes. These shared references to the data can be handed out widely, and we are not at risk of accidentally de-allocating or consolidating or otherwise transforming the data while others outside our dataflow scope are hoping we do not. This is different from providing meaningful semantic guarantees (which we will get to), but actually handing pointers around does not seem to be a limitation.

There are some considerations to make about what is guaranteed to other users, as we will update the logical contents of the trace (e.g. by compaction as time advances), but these guarantees are currently provided by the trace itself, with the underlying shared resources immutable and much easier to reason about.

---

The main handle to a trace is the appropriately named `arrange::TraceHandle` type. This type has shared ownership of [a wrapper around] a trace, and as long as it is held provides access to the trace. This is the way that operators interact with the trace.

If left alone, the trace handle provides access to the full history of the trace. It also provides the operators the opportunity to downgrade their access, by stating that certain historical times have become indistinguishable to the operator. When this happens, the trace wrapper (aware of the existence of multiple handles, with multiple frontiers of indistinguishable times) may eventually notify the trace that it can compact its state representation. The compaction updates the logical contents of the trace, but does not mutate the underlying resources (it consolidates updates at indistinguishable timestamps into new batches, which replace the existing ones).

Importantly, as the trace makes progress forward, it permanently forgets about the distinctions in the past. Other operators that may want to attach to this trace and stream of batches need to acknowledge that their view of the data, though containing all data ever introduced, can only be from the perspective of whatever times the trace has promised will remain distinguishable. Practically speaking, this means that when you attach to a collection you can see its contents "now", and watch their changes from this point on; you may not be able to get access to the changes the collection experienced five minutes ago.

The trace and trace handle also provide another capability, which is relatively new but seemingly important: the ability to bookmark batches and receive the trace restricted to only those updates through the bookmarked batch. This seems crucial for correct behavior of `join`, and implementation-wise is relatively simple: merging is blocked wherever these bookmarks exist. Any new references to the trace need to accept and understand the restriction on bookmarks just as with compaction: their opportunities are restricted by the state of the trace when they attach to it.

---

It is not hard to export a trace handle from the scope it was produced in; the `example/arrange.rs` example does exactly this. The trace handle can simply be cloned and returned from the scope, as it contains no references to the scope, only to the timestamp of the scope. 

Can use a trace handle to populate a new operator in another dataflow scope. Or perhaps more appropriately: can we create a new `Arrangement` in another scope, a pair of trace handle and stream of immutable batches?

The trace handle part seems relatively easy: we have a trace handle, and it is safe to clone. The stream is more complicated, as we cannot exfiltrate the existing stream of updates from the dataflow scope in which they exist. Can we create a new operator which taps into the sequence of batches and reposts them in this other scope? 

There is precedent for extracting a stream from one scope and replaying it in another dataflow scope: timely dataflow's `capture` and `replay` operators. These operators give us a clue about the moving parts we might require, but are not themselves sufficient (they capture and replay the entire history of the stream; unboundedly much data). The `replay` operator defines a new timely dataflow operator, and consults a shared sequence of observations made by `capture` to drive its behavior: both records produced and progress indicated.

I believe most of the complexity of shared arrangements between dataflow scopes lies in the design of this operator, so let's talk about it.

---

To write a timely dataflow operator using the generic tools, we need to do a few things. We might need to hand-roll everything because our intended operator has no inputs, but ignoring that let's talk through what we need to sort out.

Each timely dataflow operator, and especially inputs, need to specify what initial capabilities they require. Without initial capabilities, an operator with no inputs will never acquire capabilities and can never send anything. So we want some initial capabilities so that the operator can act as a source of data. Conventionally, we just take `T::min()` as the initial capability, and then downgrade it once we get started. If it were helpful, we could think harder about the state of affairs in the trace and start with an advanced timestamp, but it isn't clear if this is helpful; if it ever becomes helpful the option exists.

In operation, a timely dataflow operator needs to indicate what it does each time it gets tickled, which in our restricted setting includes (i) the sending of batches, and (ii) the downgrading of output capabilities. In essence, we would like our operator to replay the actions of the source `arrange` operator, and can imagine a shared queue from the source operator into which batches are deposited. Each batch is "self-describing", in that it has an upper and lower bound on the times contained within. Assuming a FIFO queue, the upper bound in an observed batch is the input frontier at the source operator at the time the batch was minted. These upper bounds should allow the proxy operator to manage its capabilities, conservatively.

Importantly, the proxy operator should not track the capabilities of the source operator; the source operator only holds capabilities for updates it is currently buffering, and it may receive new updates with upgraded capabilities in the future. Timely dataflow is paying attention to that, and ensuring that downstream consumers do not get carried away. The proxied operator does not have this benefit, and must present the full view of progress information, which is what is reflected by the input frontier to the source arrange operator.

Although the upper bounds in the descriptions of the produced batches typically track this input frontier, they can lag behind in empty regions of time: although the arrange operator can see that it can mint a new empty batch with advanced upper bounds, from its input frontier, it cannot *send* this batch to anyone as it lacks the capability to do so. In the source dataflow scope this is not a problem, as downstream operators use the progress information provided by timely dataflow. In the proxy scope, we do not have this benefit. Instead, the source arrange operator can explicitly communicate that its frontier has advanced, if this happens when it cannot send a batch. Probably the best way to do this is to allow the shared queue to have two types of content: a batch and a progress statement. Other options include putting an empty batch with the right bounds into the shared queue, but we diverge from "exactly the same stream" at this point, and operator logic may be subtly wrong or different.

---

To sum up, I propose adding an initially empty shared list of shared queues in the `arrange` operator, extending the trace handle to have access to this shared list, and creating a new method that will mint  a new operator, mint and register a new shared queue, and produce a new `Arrangement` reflecting the handle and the new stream.

The registration process should do a few things; in addition to adding the queue to the list, it should probably push copies of all existing batches into the queue, so that the operators see the accumulated history. Most operators require this for correct operation. I believe this should "just work" in that these batches are also self-describing, and the proxy operators behavior on seeing them should be no different than its behavior when it receives new batches.

The behavior of the `arrange` operator will likely need to be slightly enriched, so that it not only enqueues batches in each shared queue, but also observes the advance of its input frontier and interacts with the queues even when it cannot create and send batches along its outputs. This seems mostly straightforward, but who knows.

--- 

I can imagine a few possible issues, or things to think about:

1. The bookmark functionality is under-specified at the moment. The main user, `join`, may get stressed out when it sees batches but cannot use the bookmarks corresponding to their bounds (as part of the replayed historical batches). This may not be a problem in the current code, because `join` drains each input completely before reflecting on bookmarks, and so doesn't worry about intermediate bookmarks, but the lack of problem would be by good luck rather than sane design.

2.  I'm not entirely certain what will happen when we feed a `group` operation with advanced batch data. At the moment there is no guarantee that the times in the data have any semantic meaning other than that they compare equivalently to future times. Thus, we may do crazy things like advance initial increments *past* subsequent decrements; replaying the collection as indicated would suggest transiently negative counts.

    I expect this to be pretty broken, really. It may require a careful thinking through of operators and what they are allowed to assume about the times in their batches. We might require that all times be "caught up" before they are used, something we do not do at the moment because of course a newly received batch is in advance of previously received batches, right? 

    We could also consider the advancement strategy, so that old updates cannot be advanced past newer updates; we would need to be pretty thoughtful to guarantee that we only see transient collections that actually existed. For example, if whenever we advance we advance all batches in the trace, to a frontier no greater than future batches that may arrive, we should always have batches with some sane properties (and consistent advancement has other benefits: updates are more likely to cancel if advanced to the same frontier).

3.  As we hand out more handles to the trace, we have more operators that can impose requirements on the shared trace. The more folks who make bookmarks, or who require the trace be held back from consolidation, the less efficient the representation and the more work done by other operators. This might be enough of a pain-point to start to develop more robust traces: for example, we can start merging batches even with bookmarks within them, as long as we do not yet discard the old batches. Oblivious users can use the merged batches and faster cursors. Likewise, we could start speculatively advancing batches, retaining old batches for users that require them but providing the partially redundant compacted batches to users that do not. As the bounds advance, we just discard the old data and pivot to the new, rather than panicking to produce the new data.

    For now, I think we can ignore this and just see what happens.

**Comment by frankmcsherry** [comment]
Each batch description currently contains, in addition to its lower and upper bounds, a frontier `since` which tracks the lower bound on times against which the times in the batch can be correctly compared. It would not be too complicated to examine this field when processing a sequence of batches, and acting on regressions (namely, advancing times to the most advanced `since` frontier, rather than trusting the times in the batch to be current).

From a different perspectives, trace implementations are currently expected to maintain a contiguous sequence of batches, where the upper bound of one batch equals the lower bound of the next batch. However, there is no requirement on the `since` fields; it could be sane to insist that they are non-decreasing as batches, a property that does not currently hold. We could insist that it hold (forcing spines to either advance all held batches simultaneously, or to be less aggressive in advancement), or we could expect operators to take remedial action.

I'm opposed to pushing correctness properties down to the operators, but I don't fully understand the cost to the traces yet either; if it is wildly expensive for a trace to maintain an invariant that is only useful for subsequently started computations, and only transiently as they start up, perhaps it should be handled as exceptional behavior rather than an invariant.

**Comment by frankmcsherry** [comment]
Thinking  a bit further, I'm less stressed out about the compaction. Although things can be weird in principle, in practice advancement currently only happens when we merge the largest batch, which means that all smaller batches are absent. Each time we advance, all held batches (non-bookmarked ones, anyhow) are advanced to the same frontier. Subsequent batches should have subsequent `since` fields.

The only exception to this is if the advance frontier outpaces bookmarks, so that we have some bookmarked (not merged) batches that are not being advanced. This seems pretty easy to watch for and correct, either by advancing to the lower bound of the advance frontier and the least bookmark, or by advancing bookmarked batches on introduction. I suspect that the former is limited, as if that made sense we would just have bookmarks and no advance frontier. The `join` operator is the one that distinguishes between the two most clearly, and is worth checking out.

**Comment by frankmcsherry** [comment]
We have shared arrangements at the moment, and while they could be better spec'd out, I'm going to close this for now.

**Comment by ryzhyk** [comment]
@frankmcsherry , I came across this thread when searching for the capability to share arrangements across scopes. Specifically, some of my programs could save a lot of memory by sharing arrangements between child and parent scopes. Your last comment seems to suggest that this has been implemented. Is that indeed the case? Which API should I use to take advantage of this capability?

Thanks!

**Comment by frankmcsherry** [comment]
You should be able to share an arrangement in a parent scope with a child scope via the `enter(child_scope)` method on an arrangement. [This line here](https://github.com/TimelyDataflow/differential-dataflow/blob/master/examples/arrange.rs#L116) is an example where this happens. It looks the same as the line below it, but the type of `edges` is an arrangement.

There is not a story for sharing an arrangement in a child scope with its parent scope, because doing so would violate some invariants that currently exist. Maybe in the future, but for the moment this is sufficiently problematic as to not be something I have by brain around.

**Comment by ryzhyk** [comment]
Understood, thanks! I already use the parent->child sharing and was wondering about the other direction. I realize it is hard and may not happen soon. But just for the record, if one day you have absolutely nothing on your todo list :) and are deciding what feature to implement next, I think this one would be useful in many recursive programs.
