### ISSUE TITLE
Batches contain more `Rc` that one might want

### ISSUE THREAD

**Issue by frankmcsherry** [frankmcsherry/differential-dataflow#61]
The batch implementations currently use `Rc` somewhat liberally, mostly in support of easily written cursors that can own layers of the batch (the allocations containing keys, values, times, etc). This seems relatively harmless in normal function, as the batches themselves are wrapped with `Rc` and liberally shared where possible; they are intended to be immutable, and treated as such.

However, certain bits of logic would be much simpler if each batch was uniquely owned. The main one I'm thinking of at the moment is durability, where we would like to be able to serialize and deserialize such an object with something like Abomonation, i.e. just mapping some memory, but the existence of `Rc` internal to the type makes this not possible (`Rc` is not safe to abomonate, due to the `Cell` wrappers around the counts, which are meant to keep allocations alive but wouldn't).

Another less critical example, `advance_mut` is the method that transforms a batch into one where times have been advanced to the current frontier, and it is intended to allow this to happen in place if there is unique ownership of the underlying resources. This is relatively easy to sort out if there is one `Rc` around the batch, and more complicated if there are several `Rc`s inside as well.

The main benefit of the internal `Rc` types is that cursors can be written independently for each layer, taking (shared) ownership of the layer rather than worrying about borrowing it. This allows us to write cursors modularly, and compose them easily. If we removed the option of shared ownership, we would seemingly need to either (i) rewrite cursors as acting on borrowed slices, or (ii) write a cursor monolithically, taking (shared) ownership of the whole batch.

Some thoughts on each:

1. Borrowing is annoying, but there is reason to think that we might eventually want this anyhow, if we end up with indices in each trace (from key to locations in a subset of batches). These indices need to be borrowed, rather than shared, (the benefit is that they are updated in place), and so we end up with a borrow anyhow.

2. Monolithic cursor writing doesn't need to be complicated, as the cursor side of the trace layers is pretty simple (compared to the merge logic, which is a bit more complicated and should stay modular, in my opinion). It is probably worth prototyping this out to see if it is horrid or not.

In either case, we may need to rethink "what is a batch" to understand whether it is something pre-`Rc`d, or whether it is something we should expect to wrap in a `Rc`. I am inclined toward making `Batch : Clone` with the understanding that the clone implementation should be relatively efficient (i.e. will be called regularly). If this means an internal `Rc` great, and outside of the batch we won't wrap it in one.

**Comment by utaal** [comment]
I may have a compromise approach that works for this: no `Rc`s, no explicit borrowing, a new dependency (`OwningRef`). More details tomorrow.
